### ISSUE TITLE
Generate hash from STDIN

### ISSUE THREAD

**Issue by heywoodlh** [Eugeny/warpgate#15]
It'd be nice to be able to generate a password hash by passing it to `warpgate hash` via STDIN, like so:

```
echo -n 'mypass' | warpgate hash
```

**Comment by Eugeny** [comment]
Good catch - there's already a stdin mode, but it currently doesn't get activated if _stdout_ is a TTY - here's a workaround: `echo -n 'mypass' | warpgate hash | cat`

**Comment by heywoodlh** [comment]
Huh weird. I'll switch it to a weekly build if that is okay with you.

**Comment by Eugeny** [comment]
Sure, or just remove the build part or switch it to your own image registry so that it doesn't fail
